/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package personnel;

import java.awt.Color;
import java.awt.Container;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ashwin Rajan
 */
public class CommonEntryForm extends javax.swing.JFrame {

    //**********Declaring Global Variable********************************
    String firstName;
    String lastName;
    String dateOfBirth;
    String phoneNumber;
    String departmentName;
    String socialSecurityNumber;
    String annualSalary;
    String streetAddress;
    String cityName;
    String streetNum = " ";
    String streetName = " ";
    String postalCode;
    String provinceName;
    String majorFieldOfStudy;
    String gradePointAverage;

    public CommonEntryForm() {
        initComponents();

        Color c = new Color(0, 51, 255);
        Container con = this.getContentPane();
        con.setBackground(c);

        this.setLocation(450,150);
        
    }

    //********setLabel12Text method**********************
    public void setLabel12Text(String text) {

        jLabel12.setText(text);

    }

    //********setPanel5Visiblity method**********************
    public void setPanel5Visiblity(boolean visiblity) {

        jPanel5.setVisible(visiblity);

    }

    //********setPanel6Visiblity method**********************
    public void setPanel6Visiblity(boolean visiblity) {

        jPanel6.setVisible(visiblity);

    }

    //********setLabel5Text method**********************
    public void setLabel5Text(String text) {

        jLabel5.setText(text);

    }

    //********setLabel7Text method**********************
    public void setLabel7Text(String text) {

        jLabel7.setText(text);

    }

    //********setLabel6Visiblity method**********************
    public void setLabel6Visiblity(boolean visiblity) {

        jLabel6.setVisible(visiblity);

    }

    //********setTextField6Visiblity method**********************
    public void setTextField6Visiblity(boolean visiblity) {

        jTextField6.setVisible(visiblity);

    }

    //********setCheckBox1Visiblity method**********************
    public void setCheckBox1Visiblity(boolean visiblity) {

        jCheckBox1.setVisible(visiblity);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("First Name:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Last Name:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Date of Birth:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Phone Number:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Department Name:");

        jTextField1.setBackground(new java.awt.Color(0, 102, 255));
        jTextField1.setForeground(new java.awt.Color(255, 255, 0));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(0, 102, 255));
        jTextField2.setForeground(new java.awt.Color(255, 255, 0));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(0, 102, 255));
        jTextField3.setForeground(new java.awt.Color(255, 255, 0));

        jTextField4.setBackground(new java.awt.Color(0, 102, 255));
        jTextField4.setForeground(new java.awt.Color(255, 255, 0));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(0, 102, 255));
        jTextField5.setForeground(new java.awt.Color(255, 255, 0));

        jPanel5.setBackground(new java.awt.Color(0, 51, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true));
        jPanel5.setVisible(false);

        jRadioButton1.setBackground(new java.awt.Color(0, 51, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 0));
        jRadioButton1.setText("Tenured");
        jPanel5.add(jRadioButton1);

        jRadioButton2.setBackground(new java.awt.Color(0, 51, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 0));
        jRadioButton2.setText("Non-Tenured");
        jPanel5.add(jRadioButton2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Social Security Number:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Annual Salary:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Street Address:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("City Name:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Postal Code:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Province:");

        jTextField6.setBackground(new java.awt.Color(0, 102, 255));
        jTextField6.setForeground(new java.awt.Color(255, 255, 0));
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });

        jTextField7.setBackground(new java.awt.Color(0, 102, 255));
        jTextField7.setForeground(new java.awt.Color(255, 255, 0));
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        jTextField8.setBackground(new java.awt.Color(0, 102, 255));
        jTextField8.setForeground(new java.awt.Color(255, 255, 0));

        jTextField9.setBackground(new java.awt.Color(0, 102, 255));
        jTextField9.setForeground(new java.awt.Color(255, 255, 0));

        jTextField10.setBackground(new java.awt.Color(0, 102, 255));
        jTextField10.setForeground(new java.awt.Color(255, 255, 0));
        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });

        jTextField11.setBackground(new java.awt.Color(0, 102, 255));
        jTextField11.setForeground(new java.awt.Color(255, 255, 0));
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SheridanLogo.JPG"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(0, 51, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true), "Course Info:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 12), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel6.setVisible(false);

        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Name:");

        jTextField12.setBackground(new java.awt.Color(0, 102, 255));
        jTextField12.setForeground(new java.awt.Color(255, 255, 0));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText(" Number:");

        jTextField13.setBackground(new java.awt.Color(0, 102, 255));
        jTextField13.setForeground(new java.awt.Color(255, 255, 0));
        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField13FocusLost(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(255, 255, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("Credit:");

        jTextField14.setBackground(new java.awt.Color(0, 102, 255));
        jTextField14.setForeground(new java.awt.Color(255, 255, 0));
        jTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField14FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField13)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField14)
                        .addComponent(jLabel17)))
                .addContainerGap())
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
        );

        jCheckBox1.setBackground(new java.awt.Color(0, 51, 255));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox1.setText("Add a Course");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jCheckBox1.setVisible(false);

        jCheckBox2.setBackground(new java.awt.Color(0, 51, 255));
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox2.setText("Lab Course");
        jCheckBox2.setVisible(false);

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/go-back-icon.png"))); // NOI18N
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Save-icon.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Exit-icon.png"))); // NOI18N
        jButton3.setText("Quit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(85, 85, 85)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jCheckBox1)
                            .addGap(27, 27, 27)
                            .addComponent(jCheckBox2))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 30, 19);
        getContentPane().add(jPanel4, gridBagConstraints);

        jMenu1.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/go-back-icon.png"))); // NOI18N
        jMenuItem1.setText("Go Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Save-icon.png"))); // NOI18N
        jMenuItem2.setText("Save");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Exit-icon.png"))); // NOI18N
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/About-icon.png"))); // NOI18N
        jMenuItem8.setText("About");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //********Close Program********************************************
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //***********Execute the following code if user create College Employee********************
        if (MainForm.collegeemployeeCreated == true) {

            if ("".equals(jTextField1.getText()) || "".equals(jTextField2.getText()) || "".equals(jTextField3.getText()) || "".equals(jTextField4.getText())
                    || "".equals(jTextField5.getText()) || "".equals(jTextField6.getText()) || "".equals(jTextField7.getText()) || "".equals(jTextField8.getText())
                    || "".equals(jTextField9.getText()) || "".equals(jTextField10.getText()) || "".equals(jTextField11.getText())) {

                jLabel13.setText("Incomplete Above Fields");


            } else {

                jLabel13.setText("");

                dateOfBirth = jTextField3.getText();
                phoneNumber = jTextField4.getText();
                departmentName = jTextField5.getText();
                annualSalary = jTextField7.getText();
                streetAddress = jTextField8.getText();
                cityName = jTextField9.getText();


                double annualSalaryDouble = Double.parseDouble(annualSalary);
                //**************************************************************************************************

                //********Separating street number and street name***************************************************
                for (int i = 0; i < streetAddress.length(); i++) {

                    streetNum += streetAddress.charAt(i);

                    if (streetAddress.charAt(i) == ' ') {

                        for (int j = i + 1; j < streetAddress.length(); j++) {

                            streetName += streetAddress.charAt(j);

                        }
                        break;

                    }
                }
                //***************************************************************************************************

                //*********Creates a CollegeEmployee text file and write all the information about the CollegeEmployee************
                FileWriter myinput = null;

                try {

                    File file = new File("CollegeEmployee.txt");
                    myinput = new FileWriter(file, true);
                    CollegeEmployee personCollegeEmployee;


                    personCollegeEmployee = new CollegeEmployee(firstName, lastName, streetNum, streetName, cityName, provinceName, postalCode,
                            dateOfBirth, phoneNumber, socialSecurityNumber, departmentName, annualSalaryDouble);

                    // Write formatted output to the file
                    myinput.append(personCollegeEmployee.toString());
                    myinput.close();


                } catch (IOException ex) {
                    Logger.getLogger(CommonEntryForm.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        myinput.close();
                    } catch (IOException ex) {
                        Logger.getLogger(CommonEntryForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                //********************************************************************************************************

                this.dispose();
                this.jButton1ActionPerformed(evt);

            }

        } //***********Execute the following code if user create Faculty********************
        else if (MainForm.facultyCreated == true) {

            if ("".equals(jTextField1.getText()) || "".equals(jTextField2.getText()) || "".equals(jTextField3.getText()) || "".equals(jTextField4.getText())
                    || "".equals(jTextField5.getText()) || "".equals(jTextField6.getText()) || "".equals(jTextField7.getText()) || "".equals(jTextField8.getText())
                    || "".equals(jTextField9.getText()) || "".equals(jTextField10.getText()) || "".equals(jTextField11.getText())) {

                jLabel13.setText("Incomplete Above Fields");


            } else if (jRadioButton1.isSelected() == false && jRadioButton2.isSelected() == false) {

                jLabel13.setText("Incomplete Above Fields");
            } else {

                jLabel13.setText("");
                dateOfBirth = jTextField3.getText();
                phoneNumber = jTextField4.getText();
                departmentName = jTextField5.getText();
                annualSalary = jTextField7.getText();
                streetAddress = jTextField8.getText();
                cityName = jTextField9.getText();
                boolean tenurned = false;


                double annualSalaryDouble = Double.parseDouble(annualSalary);
                //**************************************************************************************************

                //********Separating street number and street name***************************************************
                for (int i = 0; i < streetAddress.length(); i++) {

                    streetNum += streetAddress.charAt(i);

                    if (streetAddress.charAt(i) == ' ') {

                        for (int j = i + 1; j < streetAddress.length(); j++) {

                            streetName += streetAddress.charAt(j);

                        }
                        break;

                    }
                }
                //***************************************************************************************************

                if (jRadioButton1.isSelected() == true) {

                    tenurned = true;

                } else if (jRadioButton2.isSelected() == true) {

                    tenurned = false;

                }
                //*****************************************************************************************************

                //*********Creates a Faculty text file and write all the information about the Faculty************
                FileWriter myinput = null;

                try {

                    File file = new File("Faculty.txt");
                    myinput = new FileWriter(file, true);
                    Faculty personFaculty;

                    personFaculty = new Faculty(firstName, lastName, streetNum, streetName, cityName, provinceName, postalCode,
                            dateOfBirth, phoneNumber, socialSecurityNumber, departmentName, annualSalaryDouble, tenurned);

                    // Write formatted output to the file
                    myinput.append(personFaculty.toString());
                    myinput.close();


                } catch (IOException ex) {
                    Logger.getLogger(CommonEntryForm.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        myinput.close();
                    } catch (IOException ex) {
                        Logger.getLogger(CommonEntryForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                //**************************************************************************************************

                this.dispose();
                this.jButton1ActionPerformed(evt);

            }

        } //***********Execute the following code if user create Student********************
        else if (MainForm.studentCreated == true) {

            boolean correct = false;
            Student personStudent = null;

            if ("".equals(jTextField1.getText()) || "".equals(jTextField2.getText()) || "".equals(jTextField3.getText()) || "".equals(jTextField4.getText())
                    || "".equals(jTextField5.getText()) || "".equals(jTextField7.getText()) || "".equals(jTextField8.getText())
                    || "".equals(jTextField9.getText()) || "".equals(jTextField10.getText()) || "".equals(jTextField11.getText())) {

                jLabel13.setText("Incomplete Above Fields");


            } else if (jCheckBox1.isSelected() == true) {

                if ("".equals(jTextField12.getText()) || "".equals(jTextField13.getText()) || "".equals(jTextField14.getText())) {

                    jLabel13.setText("Incomplete Above Fields");


                } else {

                    jLabel13.setText("");
                    dateOfBirth = jTextField3.getText();
                    phoneNumber = jTextField4.getText();
                    majorFieldOfStudy = jTextField5.getText();
                    gradePointAverage = jTextField7.getText();
                    streetAddress = jTextField8.getText();
                    cityName = jTextField9.getText();
                    String department = jTextField12.getText();
                    String courseNumber = jTextField13.getText();
                    String credits = jTextField14.getText();
                    correct = true;


                    //********Separating street number and street name***************************************************
                    for (int i = 0; i < streetAddress.length(); i++) {

                        streetNum += streetAddress.charAt(i);

                        if (streetAddress.charAt(i) == ' ') {

                            for (int j = i + 1; j < streetAddress.length(); j++) {

                                streetName += streetAddress.charAt(j);

                            }
                            break;

                        }
                    }
                    //***************************************************************************************************

                    double gpa = Double.parseDouble(gradePointAverage);

                    int courseNumberInt = Integer.parseInt(courseNumber);

                    int creditsInt = Integer.parseInt(credits);
                    //************************************************************************************************

                    if (jCheckBox2.isSelected() == true) {

                        boolean labCourse = true;

                        personStudent = new Student(firstName, lastName, streetNum, streetName, cityName, provinceName, postalCode,
                                dateOfBirth, phoneNumber, majorFieldOfStudy, gpa, department, courseNumberInt, creditsInt, labCourse);

                    } else {

                        personStudent = new Student(firstName, lastName, streetNum, streetName, cityName, provinceName, postalCode,
                                dateOfBirth, phoneNumber, majorFieldOfStudy, gpa, department, courseNumberInt, creditsInt);
                    }



                }


            } else {

                jLabel13.setText("");
                dateOfBirth = jTextField3.getText();
                phoneNumber = jTextField4.getText();
                majorFieldOfStudy = jTextField5.getText();
                gradePointAverage = jTextField7.getText();
                streetAddress = jTextField8.getText();
                cityName = jTextField9.getText();
                correct = true;


                //********Separating street number and street name***************************************************
                for (int i = 0; i < streetAddress.length(); i++) {

                    streetNum += streetAddress.charAt(i);

                    if (streetAddress.charAt(i) == ' ') {

                        for (int j = i + 1; j < streetAddress.length(); j++) {

                            streetName += streetAddress.charAt(j);

                        }
                        break;

                    }
                }
                //***************************************************************************************************


                double gpa = Double.parseDouble(gradePointAverage);
                //*************************************************************************************************

                personStudent = new Student(firstName, lastName, streetNum, streetName, cityName, provinceName, postalCode,
                        dateOfBirth, phoneNumber, majorFieldOfStudy, gpa);


            }

            //*********Creates a Student text file and write all the information about the Student************

            if (correct == true) {

                FileWriter myinput = null;
                try {

                    File file = new File("Student.txt");
                    myinput = new FileWriter(file, true);

                    // Write formatted output to the file
                    myinput.append(personStudent.toString());
                    myinput.close();


                } catch (IOException ex) {
                    Logger.getLogger(CommonEntryForm.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        myinput.close();
                    } catch (IOException ex) {
                        Logger.getLogger(CommonEntryForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                //*****************************************************************************************************
                
                this.dispose();
                this.jButton1ActionPerformed(evt);

            }


        }



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //*****Go Back To Main Form*****************************************
        this.dispose();
        MainForm.collegeemployeeCreated = false;
        MainForm.facultyCreated = false;
        MainForm.studentCreated = false;

        MainForm mainform = new MainForm();

        mainform.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:


        //********First Name Validation***************************************************************************

        firstName = jTextField1.getText();


        for (int i = 0; i < firstName.length(); i++) {

            if (Character.isLetter(firstName.charAt(i)) == false) {

                jLabel13.setText("First Names should contain only alphabets, no digits, no spaces.");
                jTextField1.requestFocus();
                jTextField1.setBackground(Color.RED);
                jTextField1.selectAll();
                break;

            } else {

                jLabel13.setText("");

                jTextField1.setBackground(new Color(0, 102, 255));
            }

        }

    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:


        //********Last Name Validation***************************************************************************

        lastName = jTextField2.getText();


        for (int i = 0; i < lastName.length(); i++) {

            if (Character.isLetter(lastName.charAt(i)) == false) {

                jLabel13.setText("Last Names should contain only alphabets, no digits, no spaces.");
                jTextField2.requestFocus();
                jTextField2.setBackground(Color.RED);
                jTextField2.selectAll();
                break;

            } else {

                jLabel13.setText("");

                jTextField2.setBackground(new Color(0, 102, 255));

            }

        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        // TODO add your handling code here:

        //********Social Security Number Validation***************************************************************************

        socialSecurityNumber = jTextField6.getText();

        if (("".equals(socialSecurityNumber)) == false) {


            if (socialSecurityNumber.length() != 9) {

                jLabel13.setText("SIN number should be 9 digits");
                jTextField6.requestFocus();
                jTextField6.setBackground(Color.RED);
                jTextField6.selectAll();

            } else {

                for (int i = 0; i < socialSecurityNumber.length(); i++) {

                    if (Character.isDigit(socialSecurityNumber.charAt(i)) == false) {

                        jLabel13.setText("SIN number should contain only digits, no spaces.");
                        jTextField6.requestFocus();
                        jTextField6.setBackground(Color.RED);
                        jTextField6.selectAll();
                        break;

                    } else {

                        jLabel13.setText("");

                        jTextField6.setBackground(new Color(0, 102, 255));
                    }

                }


            }
        }


    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        // TODO add your handling code here:

        //********Postal Code Validation***************************************************************************

        postalCode = jTextField10.getText();

        if (("".equals(postalCode)) == false) {

            if (postalCode.length() == 6) {

                if ((Character.isLetter(postalCode.charAt(0)) & Character.isLetter(postalCode.charAt(2)) & Character.isLetter(postalCode.charAt(4))
                        & Character.isDigit(postalCode.charAt(1)) & Character.isDigit(postalCode.charAt(3)) & Character.isDigit(postalCode.charAt(5))) == false) {

                    jLabel13.setText("Postal code should be in the format (alphabet digit alphabet digit alphabet digit)");
                    jTextField10.requestFocus();
                    jTextField10.setBackground(Color.RED);
                    jTextField10.selectAll();

                } else {
                    postalCode = postalCode.toUpperCase();
                    jLabel13.setText("");
                    jTextField10.setBackground(new Color(0, 102, 255));

                }
            } else {

                jLabel13.setText("Postal code should be in the format (alphabet digit alphabet digit alphabet digit)");
                jTextField10.requestFocus();
                jTextField10.setBackground(Color.RED);
                jTextField10.selectAll();
            }
        }


    }//GEN-LAST:event_jTextField10FocusLost

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        // TODO add your handling code here:

        //********Province Name Validation***************************************************************************

        provinceName = jTextField11.getText();
        if (("".equals(provinceName)) == false) {

            if (provinceName.length() != 2) {

                jLabel13.setText("Province should be 2 character long & (No Digits)");
                jTextField11.requestFocus();
                jTextField11.setBackground(Color.RED);
                jTextField11.selectAll();

            } else {

                if ((Character.isLetter(provinceName.charAt(0)) & Character.isLetter(provinceName.charAt(1))) == false) {

                    jLabel13.setText("Province should be 2 character long & (No Digits)");
                    jTextField11.requestFocus();
                    jTextField11.setBackground(Color.RED);
                    jTextField11.selectAll();

                } else {

                    provinceName = provinceName.toUpperCase();
                    jLabel13.setText("");
                    jTextField11.setBackground(new Color(0, 102, 255));

                }
            }
        }


    }//GEN-LAST:event_jTextField11FocusLost

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:

        //******Show lab course checkbox only if user select add a course*********************************
        if (jCheckBox1.isSelected()) {

            jCheckBox2.setVisible(true);
            jPanel6.setVisible(true);

        } else {

            jCheckBox2.setVisible(false);
            jPanel6.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.jButton1ActionPerformed(evt);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:

        //********TextField Should contain only digits***************************************************************************

        for (int i = 0; i < jTextField7.getText().length(); i++) {

            if ((Character.isLetter(jTextField7.getText().charAt(i)) == true)) {


                jLabel13.setText("Should contain only digits, no spaces.");
                jTextField7.requestFocus();
                jTextField7.setBackground(Color.RED);
                jTextField7.selectAll();
                break;

            } else {

                jLabel13.setText("");

                jTextField7.setBackground(new Color(0, 102, 255));
            }

        }

    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusLost
        // TODO add your handling code here:

        //********TextField Should contain only digits***************************************************************************        

        for (int i = 0; i < jTextField13.getText().length(); i++) {

            if (Character.isDigit(jTextField13.getText().charAt(i)) == false) {

                jLabel13.setText("Should contain only digits, no spaces.");
                jTextField13.requestFocus();
                jTextField13.setBackground(Color.RED);
                jTextField13.selectAll();
                break;

            } else {

                jLabel13.setText("");

                jTextField13.setBackground(new Color(0, 102, 255));
            }

        }

    }//GEN-LAST:event_jTextField13FocusLost

    private void jTextField14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField14FocusLost
        // TODO add your handling code here:

        //********TextField Should contain only digits***************************************************************************

        for (int i = 0; i < jTextField14.getText().length(); i++) {

            if (Character.isDigit(jTextField14.getText().charAt(i)) == false) {

                jLabel13.setText("Should contain only digits, no spaces.");
                jTextField14.requestFocus();
                jTextField14.setBackground(Color.RED);
                jTextField14.selectAll();
                break;

            } else {

                jLabel13.setText("");

                jTextField14.setBackground(new Color(0, 102, 255));
            }

        }

    }//GEN-LAST:event_jTextField14FocusLost

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:

        //*********Display About Form************************************************

        AboutForm about = new AboutForm();

        about.setVisible(true);

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:

        //********TextField Should contain only digits***************************************************************************
        for (int i = 0; i < jTextField4.getText().length(); i++) {

            if (Character.isDigit(jTextField4.getText().charAt(i)) == false) {

                jLabel13.setText("Should contain only digits, no spaces.");
                jTextField4.requestFocus();
                jTextField4.setBackground(Color.RED);
                jTextField4.selectAll();
                break;

            } else {

                jLabel13.setText("");

                jTextField4.setBackground(new Color(0, 102, 255));
            }

        }

    }//GEN-LAST:event_jTextField4FocusLost

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        this.jButton2ActionPerformed(evt);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommonEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommonEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommonEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommonEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CommonEntryForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
