/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package checker.board;

/**
 *
 * @author Ashwin Rajan
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Checker Board");
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridLayout(8, 8));

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButton10);
        getContentPane().add(jButton9);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton8);
        getContentPane().add(jButton7);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton11);
        getContentPane().add(jButton6);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton5);
        getContentPane().add(jButton4);
        getContentPane().add(jButton12);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton13);
        getContentPane().add(jButton14);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton15);
        getContentPane().add(jButton16);

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton17);
        getContentPane().add(jButton18);

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton19);

        jButton20.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton20);
        getContentPane().add(jButton21);

        jButton22.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton22);
        getContentPane().add(jButton23);

        jButton24.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton24);
        getContentPane().add(jButton25);

        jButton26.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton26);
        getContentPane().add(jButton27);
        getContentPane().add(jButton28);

        jButton29.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton29);
        getContentPane().add(jButton30);

        jButton31.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton31);
        getContentPane().add(jButton32);

        jButton33.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton33);
        getContentPane().add(jButton34);

        jButton35.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton35);

        jButton36.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton36);
        getContentPane().add(jButton37);

        jButton38.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton38);
        getContentPane().add(jButton39);

        jButton40.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton40);
        getContentPane().add(jButton41);

        jButton42.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton42);
        getContentPane().add(jButton43);
        getContentPane().add(jButton44);

        jButton45.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton45);
        getContentPane().add(jButton46);

        jButton47.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton47);
        getContentPane().add(jButton48);

        jButton49.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton49);
        getContentPane().add(jButton50);

        jButton51.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton51);

        jButton52.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton52);
        getContentPane().add(jButton53);

        jButton54.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton54);
        getContentPane().add(jButton55);

        jButton56.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton56);
        getContentPane().add(jButton57);

        jButton58.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton58);
        getContentPane().add(jButton59);
        getContentPane().add(jButton60);

        jButton61.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton61);
        getContentPane().add(jButton62);

        jButton63.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton63);
        getContentPane().add(jButton64);

        jButton65.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton65);
        getContentPane().add(jButton66);

        jButton67.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton67);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
